### ISSUE TITLE
Availability of the dataset?

### ISSUE THREAD

**Issue by sdruskat** [athenarc/bip-ndr-workflow#1]
Hi 👋 and thank you for publishing your work [on ArXiv](https://arxiv.org/abs/2307.12794)!

In the preprint, the dataset is described as an "open dataset", and you cite version 0.1 of it (`Koloveas, P., Chatzopoulos, S., Tryfonopoulos, C., and Vergoulis, T. (2023). Bip! ndr (nodoirefs): a dataset of citations from papers without dois in computer science conferences and workshops.`) but give no indication of where the dataset can be accessed. Is this still work in progress, or a matter the citation format not providing URLs? I'd be very interested in having a look at the dataset itself.

Many thanks!

**Comment by pkoloveas** [comment]
Hi, thank you for your interest in our work.

Yes, apparently the URLs are missing from the reference list in the preprint because of the citation format. I will fix this shortly.

The current version of the dataset is hosted on zenodo with the following DOI: [doi.org/10.5281/zenodo.7962019](https://doi.org/10.5281/zenodo.7962019)

**Comment by sdruskat** [comment]
Great, thanks!
